# .github/workflows/deploy.yml
name: Build and Push to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t tu_usuario_docker/hola-mundo-web:latest .

      - name: Push Docker image to Docker Hub
        run: docker push tu_usuario_docker/hola-mundo-web:latest
